Google authentication
umair-khanzada/food-ordering-app pull request #11
Opened 2021-08-31 14:45 UTC by MuhammadHamza096

**Goal**
user can login from google account

**Work**
install react-google-login and applied login and logout feature

**Risk**
N/A

2021-08-31 14:52 UTC, ShahirZain requested changes

2021-08-31 14:52 UTC, ShahirZain commented on .eslintrc.json
> +    "no-console": "warn",
discard these changes

2021-08-31 14:52 UTC, ShahirZain commented on src/App.js
> +  console.log('isLogin', isLogin);
discard the these chages

2021-08-31 18:27 UTC, SiddiquiMonis401 commented on src/components/googleLogin/googleLogin.js
> +import { clientId } from '../../constants/constants';
Please use appropriate names, Like constants/typeOfConstants ... It will be confusing for sure constants/constants ..

2021-08-31 18:29 UTC, SiddiquiMonis401 commented on src/components/googleLogin/googleLogin.js
> +        onSuccess={responseGoogle}
Is responseGoogle is accessible here ??

2021-08-31 18:32 UTC, SiddiquiMonis401 commented on src/components/googleLogout/googleLogout.js
> +import { clientId } from '../../constants/constants';
Also change the import here

2021-09-01 09:57 UTC, SiddiquiMonis401 approved these changes

2021-09-01 11:31 UTC, merged