List menus
umair-khanzada/food-ordering-app pull request #13
Opened 2021-09-01 17:15 UTC by MuhammadHamza096

##Goal
food items now shows in cards

##Work
create card and tab component from material ui responsive 

##Risks
N/A

##Trello Link
https://trello.com/c/qgxsRN2L/10-design-a-card-for-displaying-meal-with-its-description-along-with-price

2021-09-01 19:34 UTC, SiddiquiMonis401 commented on src/Mock/Data.js
> +import curry from '../components/images/curry.jpg';
Images are consider to be an asset for the app so please make a directory called assets and keep images there ..

2021-09-01 19:40 UTC, SiddiquiMonis401 requested changes

2021-09-01 19:40 UTC, SiddiquiMonis401 commented on src/components/Button/index.js
> +      <Typography variant="button">Order Food</Typography>
I think if it is a common component we must use props to display the title of the button ..

2021-09-01 19:40 UTC, SiddiquiMonis401 commented on src/components/CardMenus/CommonCard.js
> +          // eslint-disable-next-line react/jsx-no-duplicate-props
Why are you using eslint disable for duplicate props when there isn't a duplicate prop.

2021-09-01 19:40 UTC, SiddiquiMonis401 commented on src/components/CardMenus/Tabs.js
> +          <Tab label="Active" />
What that same label "Active" n times means ... are u just render Active for all ?? If yes, then please use some appropriate name ..

2021-09-02 08:55 UTC, SiddiquiMonis401 approved these changes

2021-09-02 09:02 UTC, ShahirZain approved these changes

2021-09-02 09:05 UTC, merged