Routing and JSON task done
umair-khanzada/food-ordering-app pull request #17
Opened 2021-09-03 12:01 UTC by smyaseen

## Goal:

Routing and JSON task

## Work: 

Routing and JSON task done 

 ## Trello Link:

2021-09-03 12:38 UTC, ShahirZain requested changes

2021-09-03 12:38 UTC, ShahirZain commented on src/Features/SignUp/SignUpContainer.js
> +          <TextField label="Enter Email" onChange={(e) => setEmail(e.target.value)} type="email" variant="outlined" />
cant we define handleChange function instead of an anonymous function? Ans use handleChange for both input field

2021-09-03 14:34 UTC, SiddiquiMonis401 requested changes
You have done the work more than the branch name is meant to be please try to avoid this ..
We do need time to review the branch

2021-09-03 14:34 UTC, SiddiquiMonis401 commented on src/Features/ForgetPassword/ForgetPasswordContainer.js
> +      <Grid alignItems="center" container direction="column" justifyContent="center">
it is item of the parent grid .. If yes then use the item prop on it

2021-09-03 14:34 UTC, SiddiquiMonis401 commented on src/Features/ForgetPassword/ForgetPasswordContainer.js
> -        <Card margin="auto" maxWidth="400px" minWidth="300px">
@Haris-moin @h-qadeer has developed a Form component please use it ..

2021-09-03 14:34 UTC, SiddiquiMonis401 commented on src/Features/ForgetPassword/ducks.js
> +    case 'ForgetPassword': // must Proper const here
You should not be use this comment instead use proper constants or removed the case ..

2021-09-03 14:34 UTC, SiddiquiMonis401 commented on src/Features/Login/LoginContainer.js
> +    </Grid>
Please sync with @Haris-moin @h-qadeer to use thier forms why are you re inventing the wheel  ??

2021-09-07 08:42 UTC, SiddiquiMonis401 approved these changes

2021-09-07 08:44 UTC, ShahirZain approved these changes

2021-09-07 08:44 UTC, merged