Task/setup mongo backend
umair-khanzada/food-ordering-app pull request #18
Opened 2021-09-06 14:26 UTC by smyaseen

## Goal:

Resolve issues in develop branch, backend API setup in front end, use observable for login and signup, save and get data from database.

## Work: 

All above done

2021-09-07 15:33 UTC, SiddiquiMonis401 requested changes

2021-09-07 15:33 UTC, SiddiquiMonis401 commented on a
> -* [32mdevelop[m
What this a file does ?? This seems to be a useless file

2021-09-07 15:33 UTC, SiddiquiMonis401 commented on src/Features/Auth/Login/index.js
>      dispatch(login({ email: loginForm.email, password: loginForm.password }));
As login feature has been integrated in development branch so try to use the input entered by the user

2021-09-07 15:33 UTC, SiddiquiMonis401 commented on src/Features/Auth/actions.js
> +import { LOGIN, LOGIN_SUCCESS, LOGOUT, LOGIN_ERROR, SIGNUP } from '../../scripts/constants';
It did not seem fit to place constants in scripts directory .. please put your ActionTypes in redux folder

2021-09-07 15:33 UTC, SiddiquiMonis401 commented on src/Features/Auth/ducks.js
> +export const loginReducer = (state = { isLoggedIn: false, token: '', name: '' }, action) => {
As we are handling the whole auth logic in this reducer that name must be changed to auth reducer

2021-09-07 15:33 UTC, SiddiquiMonis401 commented on src/routes/index.js
> +          return checkRoute(route, index);
Can we use some more meaningful name here instead if check route ??

2021-09-07 15:33 UTC, SiddiquiMonis401 commented on src/routes/index.js
> +        {isLoggedIn ? (
Why we are doing this ??

2021-09-07 15:33 UTC, SiddiquiMonis401 commented on src/routes/index.js
> +        {isLoggedIn ? (
For dashboard routes and other private routes we must use the RouteConfigs array as we are using for auth

2021-09-08 07:54 UTC, ShahirZain approved these changes

2021-09-08 07:56 UTC, SiddiquiMonis401 approved these changes

2021-09-08 10:35 UTC, merged