Task/auth feature implementation
umair-khanzada/food-ordering-app pull request #19
Opened 2021-09-07 16:03 UTC by Haris-moin

### Goal:
 apply authentications on auth features and create reset password and forget password,

### Task:
As define above

2021-09-07 19:43 UTC, SiddiquiMonis401 requested changes

2021-09-09 20:39 UTC, SiddiquiMonis401 approved these changes

2021-09-09 20:39 UTC, SiddiquiMonis401 commented on src/Features/Auth/ForgetPassword/index.js
> +    let isValid = true;
Isn't it good that we make a seprate separate function validateOnSubmit and then just call that here .. ?

2021-09-09 20:39 UTC, SiddiquiMonis401 commented on src/Features/Auth/Login/index.js
> +    loginForm.map((textField) => {
Same reviews as above ..

2021-09-09 20:41 UTC, SiddiquiMonis401 reviewed
Please resolve review comments

2021-09-10 15:40 UTC, ShahirZain approved these changes

2021-09-10 15:40 UTC, merged