Task/admin master layout
umair-khanzada/food-ordering-app pull request #23
Opened 2021-09-09 08:58 UTC by smyaseen

##Goal and Work:

Created  a master layout

2021-09-09 09:58 UTC, ShahirZain commented
please make sure your base branch should be develop

On Thu, Sep 9, 2021 at 1:58 PM SMY ***@***.***> wrote:

> ##Goal and Work:
>
> Created a master layout
> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/umair-khanzada/food-ordering-app/pull/23
> Commit Summary
>
>    - merge branches
>    - fixed card alignmet issue
>    - fixed few changes
>    - added signup
>    - removed excess reducer
>    - setup login and signup observable logic
>    - nothing update..
>    - fixed code
>    - added token save
>    - Merge branch 'main' of
>    https://github.com/umair-khanzada/food-ordering-app into develop
>    - added name
>    - forgot password api integrate
>    - Merge branch 'task/setup-mongo-backend' of
>    https://github.com/umair-khanzada/food-ordering-app into develop
>    - fixed routing issues
>    - routing issues fixed, logout observable ready, fixed bugs and
>    warnings
>    - api integrated
>    - resolved PR issues
>    - fixed indent issue
>    - api integrated
>    - change done
>    - console removed
>    - Merge pull request #18 from umair-khanzada/task/setup-mongo-backend
>    - Merge branch 'develop' of
>    https://github.com/umair-khanzada/food-ordering-app into
>    intergrate-forgot-password-api
>    - naming conventions corrected
>    - actioin path corrected
>    - Merge pull request #22 from
>    umair-khanzada/intergrate-forgot-password-api
>    - created a master layout
>    - update...
>    - resolved conflicts with develop branch
>    - layout changes
>    - removed useless file
>
> File Changes
>
>    - *M* .eslintrc.json
>    <https://github.com/umair-khanzada/food-ordering-app/pull/23/files#diff-6884918dc8291219be508e05e28965b958c734def85324f3b53858ea4702090f>
>    (3)
>    - *M* db.json
>    <https://github.com/umair-khanzada/food-ordering-app/pull/23/files#diff-bd4a9ff1dadaff3890766954fd9c12347e8cea7cd9bcc189f04c59d3049158a9>
>    (50)
>    - *M* package-lock.json
>    <https://github.com/umair-khanzada/food-ordering-app/pull/23/files#diff-053150b640a7ce75eff69d1a22cae7f0f94ad64ce9a855db544dda0929316519>
>    (12)
>    - *M* package.json
>    <https://github.com/umair-khanzada/food-ordering-app/pull/23/files#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519>
>    (3)
>    - *M* src/Features/Auth/ForgetPassword/ForgetPasswordContainer.js
>    <https://github.com/umair-khanzada/food-ordering-app/pull/23/files#diff-c92f863540f623fec4927810c2dbf094f2eaf1005a7e094ba9a0431f2b6a313c>
>    (73)
>    - *M* src/Features/Auth/Login/index.js
>    <https://github.com/umair-khanzada/food-ordering-app/pull/23/files#diff-683c2f1a5362ed8ce49133285a1b828c7fef5ad51833a8c7f9977a8deb378743>
>    (15)
>    - *M* src/Features/Auth/ResetPassword/ResetPasswordContainer.js
>    <https://github.com/umair-khanzada/food-ordering-app/pull/23/files#diff-79d1a8a9eb53c4c7b50b2623139855a26f40d707de1c1a1ec475293493c7876f>
>    (4)
>    - *M* src/Features/Auth/SignUp/index.js
>    <https://github.com/umair-khanzada/food-ordering-app/pull/23/files#diff-32e2c80c0d596a8a9b66ae4677302114ce3f8d655e1e57b1d97f4891adb5276e>
>    (18)
>    - *M* src/Features/Auth/actions.js
>    <https://github.com/umair-khanzada/food-ordering-app/pull/23/files#diff-535c00c08e60a66e7cbe06c6f6f6f2510385d82cf1c5f7a3661f4a6577a2ba8e>
>    (19)
>    - *M* src/Features/Auth/ducks.js
>    <https://github.com/umair-khanzada/food-ordering-app/pull/23/files#diff-08f43f98bceec5cf4e135ff2b37060c0b7107722e3b4d18a200ca660c62a1bef>
>    (53)
>    - *M* src/Features/Auth/epics.js
>    <https://github.com/umair-khanzada/food-ordering-app/pull/23/files#diff-318feb56f820c716fda7cd47b1678fb0602e617ce7a9ee1e531fe0b3f12f085d>
>    (87)
>    - *M* src/Features/Auth/index.js
>    <https://github.com/umair-khanzada/food-ordering-app/pull/23/files#diff-51cd59efd9615e003d6b626c771812ffaa5a747ff62cdd12f6d53d1050303f0d>
>    (2)
>    - *D* src/Features/Dashboard/CardMenu.js
>    <https://github.com/umair-khanzada/food-ordering-app/pull/23/files#diff-5797d98bcf64b1a8dcb4375683079940ba4dda8bb523e3f676374a801973e008>
>    (40)
>    - *D* src/Features/Dashboard/CommonCard.js
>    <https://github.com/umair-khanzada/food-ordering-app/pull/23/files#diff-0114e71b3666de2229e63e16e5b2ea9b98f39142b3038fc8fe983e0ad973a543>
>    (126)
>    - *D* src/Features/Dashboard/Tabs.js
>    <https://github.com/umair-khanzada/food-ordering-app/pull/23/files#diff-684376f0ca0db06ac91fb52d56a8e84aebf9cc93f5e0e70f2900ae821ce5cbfb>
>    (28)
>    - *M* src/Features/Dashboard/index.js
>    <https://github.com/umair-khanzada/food-ordering-app/pull/23/files#diff-59edbda6b9bce5424d7e342ab929261881ddbc7c3b2b1f5d6010e86b2afa9ff4>
>    (4)
>    - *M* src/Features/Dashboard/route.js
>    <https://github.com/umair-khanzada/food-ordering-app/pull/23/files#diff-ce8aff47e71c7a891c09b0e4cce20ac11165e3e3681cb7c1619b8179be7546bd>
>    (4)
>    - *M* src/components/AppBar/AppBar.js
>    <https://github.com/umair-khanzada/food-ordering-app/pull/23/files#diff-76f12647623aa1cb169adf30bf4aec56ae3ce8e609f2b74b9d8bcb090f78ebe9>
>    (8)
>    - *M* src/components/Button/Button.js
>    <https://github.com/umair-khanzada/food-ordering-app/pull/23/files#diff-918fce771f95e5b4e19e110513e81067b57128e664bb677d3e9659246ac8f734>
>    (10)
>    - *M* src/components/Button/Style.js
>    <https://github.com/umair-khanzada/food-ordering-app/pull/23/files#diff-73f3ff1fff5b2eb5809782d1cfc77ae8e9cefca375c5682296998294b7f4f016>
>    (7)
>    - *M* src/components/CardMenus/CardMenus.js
>    <https://github.com/umair-khanzada/food-ordering-app/pull/23/files#diff-3d2102ba03920fbfa69e41b4bb5ff70a49e5c4a640513dd631d08dc2bf9f5abe>
>    (20)
>    - *M* src/components/CardMenus/CommonCard.js
>    <https://github.com/umair-khanzada/food-ordering-app/pull/23/files#diff-f6372b43980d867701cd85d5d119c30020f8be96fed1093d84031867f9dc099d>
>    (109)
>    - *M* src/components/CardMenus/Tabs.js
>    <https://github.com/umair-khanzada/food-ordering-app/pull/23/files#diff-7c3c5a9ae062f61dd56dfd2da97c892c7cd370ce4818ea55a200af1b85a5988e>
>    (15)
>    - *M* src/components/FormComponent/index.js
>    <https://github.com/umair-khanzada/food-ordering-app/pull/23/files#diff-d0a780f0050a092250874326f139c3ad3407e0f5cd7a378912e4e21978e36e85>
>    (7)
>    - *M* src/components/FormComponent/styles.js
>    <https://github.com/umair-khanzada/food-ordering-app/pull/23/files#diff-fe33fa227c8b5231584abe5a31391a213e1f5fca0c018877190589037b69ec4d>
>    (4)
>    - *M* src/components/TextField/Style.js
>    <https://github.com/umair-khanzada/food-ordering-app/pull/23/files#diff-eedadf97d62d2805c9a03ef067ef2407ccc165057ae3d73e1ca5d7b8c67eb08b>
>    (4)
>    - *M* src/components/sideMenu/index.js
>    <https://github.com/umair-khanzada/food-ordering-app/pull/23/files#diff-1d02af7af24f2c17816a21deb6b74a4c105c5d71d8c2bc2f705ca834193005bf>
>    (79)
>    - *M* src/index.css
>    <https://github.com/umair-khanzada/food-ordering-app/pull/23/files#diff-85da366246340e911d7a0eb9153e64137a1b31f0686c74d9aef9ae4f032cb09e>
>    (1)
>    - *R* src/redux/ActionTypes/index.js
>    <https://github.com/umair-khanzada/food-ordering-app/pull/23/files#diff-acfb05de211b3043156ad579a767e0daa044023f5195dd9a9cd5811922eecff1>
>    (3)
>    - *M* src/redux/epics/index.js
>    <https://github.com/umair-khanzada/food-ordering-app/pull/23/files#diff-3a5c29a20d7f8a60b18d50cc0242904341365fe896f7e591c88d2137ba968077>
>    (4)
>    - *M* src/redux/reducers/index.js
>    <https://github.com/umair-khanzada/food-ordering-app/pull/23/files#diff-6a845372390ad9183029961774819c24173cdfa45c032b15ced8efca94788699>
>    (7)
>    - *D* src/routes/AuthRoute.js
>    <https://github.com/umair-khanzada/food-ordering-app/pull/23/files#diff-16fff004006394fddb7a8766a52b1063a1d717bf5e11f61790249fa1e92564e3>
>    (34)
>    - *M* src/routes/Layout/MainContainer.js
>    <https://github.com/umair-khanzada/food-ordering-app/pull/23/files#diff-4e3ae9b6e9e72faa74b166bfeb2 [...]

2021-09-10 15:55 UTC, SiddiquiMonis401 requested changes

2021-09-10 15:55 UTC, SiddiquiMonis401 commented on src/Features/Auth/ducks.js
> +      return {
shouldn't it be like that ??
`return {...state, updatedState}`;

2021-09-10 15:55 UTC, SiddiquiMonis401 commented on src/Features/Auth/epics.js
> +          return of(
Must use destructuring here

2021-09-10 15:55 UTC, SiddiquiMonis401 commented on src/components/AppBar/AppBar.js
>                <StyledMenuItem onClick={() => history.push('/profile')} theme={theme}>
We should use routename here !!

2021-09-13 13:45 UTC, SiddiquiMonis401 approved these changes

2021-09-16 06:35 UTC, merged