Task/reusable form edit add
umair-khanzada/food-ordering-app pull request #27
Opened 2021-09-12 10:14 UTC by smyaseen

## Goal & Work

Develop a reusable form component for edit n delete

2021-09-13 13:45 UTC, SiddiquiMonis401 requested changes

2021-09-13 13:45 UTC, SiddiquiMonis401 commented on src/Features/Admin/OrderHistory/AddOrder/index.js
> +import AddNEditForm from '../../../../components/AddNEditForm';
Please rename it to .. AddAndEdit

2021-09-13 13:45 UTC, SiddiquiMonis401 commented on src/Features/Admin/OrderHistory/index.js
> +      <CustomTable header={header} isEditDelete onEdit={onEdit} rows={ordersHistoryList} tablewidth="80%" />
Where is delete handler ??

2021-09-13 13:45 UTC, SiddiquiMonis401 commented on src/Features/Auth/epics.js
> +          const { name } = user;
Why are you de structuring it in multiple lines ..
Can't we do it like below ??
`const {user: { name }, tokens: { refreshToken, access } }`

2021-09-13 13:45 UTC, SiddiquiMonis401 commented on src/Features/Auth/epics.js
> +      const refreshToken = { refreshToken: state.value.authReducer.refreshToken.token };
Please use destructuring :(

2021-09-13 13:45 UTC, SiddiquiMonis401 commented on src/components/AddNEditForm/index.js
> +const AddNEditForm = ({ fields }) => {
Rename it to AddAndEdit Form

2021-09-13 13:45 UTC, SiddiquiMonis401 commented on src/components/AddNEditForm/index.js
> +const AddNEditForm = ({ fields }) => {
And I think if this is common Form use some appropriate naming for it instead of using AddAndEdit form ..
Like CommonGridBasedForm

2021-09-13 13:45 UTC, SiddiquiMonis401 commented on src/routes/index.js
> +        {isLoggedIn &&
Why we are checking this isLoggedInFlag here this means that if some wants to access this component he will get the error PageNotFound but it should be unauthorized ..

2021-09-15 06:50 UTC, smyaseen commented
Changes have been resolved.

2021-09-16 07:16 UTC, SiddiquiMonis401 approved these changes

2021-09-16 11:34 UTC, sukhan-nisum-com approved these changes

2021-09-16 11:35 UTC, ShahirZain approved these changes

2021-09-16 12:10 UTC, merged