redesign auth reusable form componen
umair-khanzada/food-ordering-app pull request #35
Opened 2021-09-16 12:40 UTC by Haris-moin

### Goal 
redesign auth reusable form
### Task
as above

2021-09-16 15:19 UTC, ShahirZain requested changes

2021-09-16 15:19 UTC, ShahirZain commented on src/components/CustomTable/style.js
> +import { TableCell } from '@material-ui/core';
why did you import it separately?

2021-09-17 07:25 UTC, SiddiquiMonis401 approved these changes

2021-09-17 07:33 UTC, ShahirZain approved these changes

2021-09-17 07:44 UTC, merged