Task/refactor eslint inline style
umair-khanzada/food-ordering-app pull request #41
Opened 2021-09-20 06:56 UTC by smyaseen

##GOAL & WORK

Refactor where necessary, particularly

1. Inline Style to Styled Component
2. Removed commented out eslint rules
3. Excessive fields.
4. Logical refactoring of methods.

2021-09-20 08:01 UTC, ShahirZain requested changes

2021-09-20 08:01 UTC, ShahirZain commented on src/components/AppBar/Style.js
> +  border-bottom: 5px solid #00b3e3;
repalce color with its name as you define in Colors.js

2021-09-21 08:59 UTC, ShahirZain approved these changes

2021-09-21 10:27 UTC, SiddiquiMonis401 approved these changes

2021-09-21 10:28 UTC, merged