Cart journey
umair-khanzada/food-ordering-app pull request #44
Opened 2021-09-21 14:16 UTC by areebali99

### Goal:
Add to cart Journey

### Task:
merge conflicts resolved of card and drawer add to cart journey

2021-09-21 14:41 UTC, ShahirZain requested changes

2021-09-21 14:41 UTC, ShahirZain commented on src/Features/Customer/Dashboard/index.js
> +  const closeDrawer = () => {
why do we need to write explicit function for open and close drawer, while we have toggleDrawer???

2021-09-21 14:41 UTC, ShahirZain commented on src/Features/Customer/Dashboard/index.js
>                  <ArrowBackIcon fontSize="large" style={{ color: '#e91e63' }} />
remove inline styling . . .and  Color with color string

2021-09-21 14:41 UTC, ShahirZain commented on src/Features/Customer/Dashboard/index.js
>                    <b> Arham Ahmed</b>
why did you use hard coded data?

2021-09-21 14:41 UTC, ShahirZain commented on src/components/CardMenus/CardMenus.js
>  const useStyles = makeStyles((theme) => ({
remove make style . .  replace with it Styled Component

2021-09-21 14:41 UTC, ShahirZain commented on src/components/CardMenus/CardMenus.js
> +  console.log('food', foodType);
remove console

2021-09-21 14:41 UTC, ShahirZain commented on src/components/CardMenus/CardMenus.js
> +        {UserData.map((usedata, index) => {
userData is not relevant name

2021-09-21 14:41 UTC, ShahirZain commented on src/components/CardMenus/CardMenus.js
> +          const { id, name, price, type, resturantName, img } = usedata;
we can destructure on parameter level

2021-09-21 14:41 UTC, ShahirZain commented on src/components/CardMenus/CardMenus.js
> +          console.log('type', type);
there should be no console in project

2021-09-21 14:41 UTC, ShahirZain commented on src/components/CardMenus/CardMenus.js
> +          if (type === foodType) {
i did not get this if check please make it clear. What is going on here

2021-09-21 14:41 UTC, ShahirZain commented on src/components/CardMenus/CommonCard.js
>            <div style={{ marginTop: '20px', display: 'flex' }}>
remove inline styling

2021-09-21 15:36 UTC, SiddiquiMonis401 approved these changes

2021-09-24 10:36 UTC, ShahirZain approved these changes

2021-09-27 07:08 UTC, merged