Cart styling
umair-khanzada/food-ordering-app pull request #51
Opened 2021-09-27 14:25 UTC by areebali99

### Goal
styling improved after getting merged 

### work
styling improved after getting merged

2021-09-27 17:05 UTC, SiddiquiMonis401 requested changes

2021-09-27 17:05 UTC, SiddiquiMonis401 commented on src/components/Drawer/index.js
> +                            <div style={{ position: 'relative', marginLeft: '5vh' }}>
Remove inline styles

2021-09-27 17:05 UTC, SiddiquiMonis401 commented on src/components/Drawer/style.js
> +export const EmptyCartHeading = styled.h2`
Use typography here!!

2021-09-28 06:23 UTC, ShahirZain requested changes

2021-09-28 06:23 UTC, ShahirZain commented on src/Features/Customer/Dashboard/index.js
> +import { Grid } from '@material-ui/core';
we can do this in single line

2021-09-28 06:23 UTC, ShahirZain commented on src/Features/Customer/ducks.js
> +/* eslint-disable no-case-declarations */
remove

2021-09-28 08:52 UTC, SiddiquiMonis401 approved these changes

2021-09-28 14:03 UTC, ShahirZain approved these changes

2021-09-29 06:54 UTC, merged