Alert message popup
umair-khanzada/food-ordering-app pull request #53
Opened 2021-09-28 08:39 UTC by h-qadeer

### Goal
Create Pop-up message

### Work
Create Pop-up message

2021-09-30 08:56 UTC, SiddiquiMonis401 approved these changes

2021-09-30 08:56 UTC, SiddiquiMonis401 commented on package.json
> +    "notistack": "^2.0.2",
remove these packages

2021-09-30 08:56 UTC, SiddiquiMonis401 commented on src/components/AlertMessage/index.js
> +        <SuccessMessage>{MESSAGE}</SuccessMessage>
Is the message always going to be the success message ?

2021-09-30 08:56 UTC, SiddiquiMonis401 commented on src/components/AlertMessage/style.js
> +  animation: ${fadein} 0.5s, ${fadeout} 0.5s ${(props) => props.time};
we have built in animations in Material go through them

2021-09-30 08:56 UTC, SiddiquiMonis401 requested changes
please remove all consoles

2021-10-01 07:45 UTC, SiddiquiMonis401 requested changes

2021-10-01 07:45 UTC, SiddiquiMonis401 commented on package.json
> +    "@emotion/styled": "^11.3.0",
Please remove those dependicies which are not in use

2021-10-01 07:45 UTC, SiddiquiMonis401 commented on src/components/AlertMessage/alertRedux/reduc.js
> +    case 'TOGGLE_SNACKBAR_OPEN': {
Please use constants here !!

2021-10-01 07:45 UTC, SiddiquiMonis401 commented on src/components/AlertMessage/index.js
> +  } = useSelector((state) => state);
This is not the right way to write reducer for useSelector please have a look at other useSelectors..

2021-10-01 13:47 UTC, SiddiquiMonis401 approved these changes

2021-10-02 08:04 UTC, ShahirZain approved these changes

2021-10-04 08:12 UTC, merged