Task/bugfix refactor develop
umair-khanzada/food-ordering-app pull request #78
Opened 2021-10-11 09:45 UTC by smyaseen

## GOAL & WORK

1. Added Image URL feature
2. Resolved every warnings
3. Fixed bug on form validations
4. Refactor and bugfixes

2021-10-11 11:15 UTC, SiddiquiMonis401 requested changes

2021-10-11 11:15 UTC, SiddiquiMonis401 commented on src/Features/Admin/Categories/AddCategory/index.js
> +      const name = fields.map(({ value }) => value);
when we are giving name[0] below why do we need to do the map over fileds array ??

2021-10-11 11:15 UTC, SiddiquiMonis401 commented on src/Features/Admin/Users/EditUser/index.js
> +    // console.log(isValid, fields);
remove console

2021-10-11 11:15 UTC, SiddiquiMonis401 commented on src/Features/Vendor/BalanceSheet/mutations.js
> +      onError: () => {
When there is not any action that needs to be performed on success and error just remove both !!

2021-10-11 11:15 UTC, SiddiquiMonis401 commented on src/Features/Vendor/Menu/Add Menu/index.js
> +  const [, setSubmit] = useState(false);
Why we need the state setter when we did not use the state ??

2021-10-12 06:19 UTC, ShahirZain approved these changes

2021-10-12 06:32 UTC, merged